### ISSUE TITLE
Upgrade to elm/http 2.0.0?

### ISSUE THREAD

**Issue by frandibar** [ohanhi/remotedata-http#5]
Hi, any plans for upgrading to elm/http 2.0.0 ?

**Comment by ohanhi** [comment]
I will at some point. It will require rewriting a lot of the package, since the code relies on `Request` quite heavily.

**Comment by ohanhi** [comment]
Yep, almost all of the code (except for the function signatures) changed. But yeah, version 4.0.0 is now published!

**Comment by frandibar** [comment]
That was fast, thank you!
